// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: admin.proto

package server

import (
	"context"

	"go-meteor-cms/rpc/v1/admin/admin"
	"go-meteor-cms/rpc/v1/admin/internal/logic"
	"go-meteor-cms/rpc/v1/admin/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) Login(ctx context.Context, in *admin.LoginReq) (*admin.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
