// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "自增主键ID"},
		{Name: "username", Type: field.TypeString, Unique: true, Comment: "用户名"},
		{Name: "password_hash", Type: field.TypeString, Comment: "密码哈希值"},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Comment: "昵称"},
		{Name: "email", Type: field.TypeString, Nullable: true, Comment: "邮箱"},
		{Name: "phone", Type: field.TypeString, Nullable: true, Comment: "手机号"},
		{Name: "is_super", Type: field.TypeBool, Comment: "是否超级管理员", Default: false},
		{Name: "is_active", Type: field.TypeBool, Comment: "是否启用", Default: true},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, Comment: "最后登录时间"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "reset_token", Type: field.TypeString, Nullable: true, Comment: "密码重置令牌"},
		{Name: "reset_expire", Type: field.TypeTime, Nullable: true, Comment: "密码重置令牌过期时间"},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminUsersTable,
	}
)

func init() {
}
