// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminPermissionsColumns holds the columns for the "admin_permissions" table.
	AdminPermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间，用于软删除"},
		{Name: "name", Type: field.TypeString, Comment: "权限名称，如 用户管理 / 新增用户"},
		{Name: "type", Type: field.TypeInt, Comment: "权限类型：1 菜单 2 按钮 3 API", Default: 1},
		{Name: "path", Type: field.TypeString, Comment: "前端路由路径，仅菜单(type=1)使用", Default: ""},
		{Name: "component", Type: field.TypeString, Comment: "前端组件路径，如 views/user/list.vue", Default: ""},
		{Name: "icon", Type: field.TypeString, Comment: "菜单图标", Default: ""},
		{Name: "method", Type: field.TypeString, Comment: "API 方法：GET/POST/PUT/DELETE，仅 type=3 使用", Default: ""},
		{Name: "api_path", Type: field.TypeString, Comment: "API 路径，如 /admin/user/list，仅 type=3 使用", Default: ""},
		{Name: "permission", Type: field.TypeString, Comment: "权限标识，如 system:user:list", Default: ""},
		{Name: "is_active", Type: field.TypeBool, Comment: "是否启用", Default: true},
		{Name: "sort", Type: field.TypeInt, Comment: "排序", Default: 0},
		{Name: "parent_id", Type: field.TypeInt64, Nullable: true, Comment: "父级ID（用于菜单树）"},
	}
	// AdminPermissionsTable holds the schema information for the "admin_permissions" table.
	AdminPermissionsTable = &schema.Table{
		Name:       "admin_permissions",
		Comment:    "后台权限表（菜单/按钮/接口）",
		Columns:    AdminPermissionsColumns,
		PrimaryKey: []*schema.Column{AdminPermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "admin_permissions_admin_permissions_children",
				Columns:    []*schema.Column{AdminPermissionsColumns[14]},
				RefColumns: []*schema.Column{AdminPermissionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "adminpermission_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminPermissionsColumns[1]},
			},
			{
				Name:    "adminpermission_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AdminPermissionsColumns[3]},
			},
		},
	}
	// AdminRolesColumns holds the columns for the "admin_roles" table.
	AdminRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID，自增"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间，用于软删除"},
		{Name: "name", Type: field.TypeString, Unique: true, Comment: "角色名称"},
		{Name: "code", Type: field.TypeString, Unique: true, Comment: "角色编码，用于系统标识，如 SUPER_ADMIN"},
		{Name: "desc", Type: field.TypeString, Nullable: true, Comment: "角色描述", Default: ""},
		{Name: "data_scope", Type: field.TypeInt, Comment: "数据权限范围：1 全公司 / 2 本部门 / 3 部门及子部门 / 4 仅自己 / 5 自定义部门", Default: 1},
		{Name: "is_system", Type: field.TypeBool, Comment: "是否系统内置角色（禁止删除）", Default: false},
		{Name: "is_active", Type: field.TypeBool, Comment: "是否启用", Default: true},
		{Name: "sort", Type: field.TypeInt, Comment: "排序，从小到大", Default: 0},
	}
	// AdminRolesTable holds the schema information for the "admin_roles" table.
	AdminRolesTable = &schema.Table{
		Name:       "admin_roles",
		Comment:    "后台角色表",
		Columns:    AdminRolesColumns,
		PrimaryKey: []*schema.Column{AdminRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminrole_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminRolesColumns[1]},
			},
			{
				Name:    "adminrole_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AdminRolesColumns[3]},
			},
		},
	}
	// AdminRoleDeptsColumns holds the columns for the "admin_role_depts" table.
	AdminRoleDeptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间，用于软删除"},
		{Name: "role_id", Type: field.TypeInt64, Comment: "角色ID，关联 admin_roles.id"},
		{Name: "dept_id", Type: field.TypeInt64, Comment: "部门ID，关联 departments.id"},
	}
	// AdminRoleDeptsTable holds the schema information for the "admin_role_depts" table.
	AdminRoleDeptsTable = &schema.Table{
		Name:       "admin_role_depts",
		Comment:    "角色部门关联表",
		Columns:    AdminRoleDeptsColumns,
		PrimaryKey: []*schema.Column{AdminRoleDeptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminroledept_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminRoleDeptsColumns[1]},
			},
			{
				Name:    "adminroledept_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AdminRoleDeptsColumns[3]},
			},
			{
				Name:    "adminroledept_role_id_dept_id",
				Unique:  true,
				Columns: []*schema.Column{AdminRoleDeptsColumns[4], AdminRoleDeptsColumns[5]},
			},
		},
	}
	// AdminRolePermissionsColumns holds the columns for the "admin_role_permissions" table.
	AdminRolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "role_id", Type: field.TypeInt64, Comment: "角色ID，关联 admin_roles.id"},
		{Name: "permission_id", Type: field.TypeInt64, Comment: "权限ID，关联 admin_permissions.id"},
	}
	// AdminRolePermissionsTable holds the schema information for the "admin_role_permissions" table.
	AdminRolePermissionsTable = &schema.Table{
		Name:       "admin_role_permissions",
		Comment:    "角色权限关联表",
		Columns:    AdminRolePermissionsColumns,
		PrimaryKey: []*schema.Column{AdminRolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "admin_role_permissions_admin_roles_role",
				Columns:    []*schema.Column{AdminRolePermissionsColumns[3]},
				RefColumns: []*schema.Column{AdminRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "admin_role_permissions_admin_permissions_permission",
				Columns:    []*schema.Column{AdminRolePermissionsColumns[4]},
				RefColumns: []*schema.Column{AdminPermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "adminrolepermission_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminRolePermissionsColumns[1]},
			},
			{
				Name:    "adminrolepermission_role_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{AdminRolePermissionsColumns[3], AdminRolePermissionsColumns[4]},
			},
		},
	}
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "自增主键ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间，用于软删除"},
		{Name: "username", Type: field.TypeString, Unique: true, Comment: "用户名"},
		{Name: "password_hash", Type: field.TypeString, Comment: "密码哈希值"},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Comment: "昵称"},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true, Comment: "邮箱"},
		{Name: "phone", Type: field.TypeString, Nullable: true, Comment: "手机号"},
		{Name: "avatar", Type: field.TypeString, Comment: "头像 URL", Default: "/uploads/avatars/meteor-default.jpg"},
		{Name: "is_super", Type: field.TypeBool, Comment: "是否超级管理员", Default: false},
		{Name: "is_active", Type: field.TypeBool, Comment: "是否启用", Default: true},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true, Comment: "最后登录时间"},
		{Name: "reset_token", Type: field.TypeString, Nullable: true, Comment: "密码重置令牌"},
		{Name: "reset_expire", Type: field.TypeTime, Nullable: true, Comment: "密码重置令牌过期时间"},
		{Name: "dept_id", Type: field.TypeInt64, Nullable: true, Comment: "所属部门ID"},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Comment:    "后台管理员用户表",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "admin_users_departments_admin_users",
				Columns:    []*schema.Column{AdminUsersColumns[15]},
				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "adminuser_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminUsersColumns[1]},
			},
			{
				Name:    "adminuser_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{AdminUsersColumns[3]},
			},
		},
	}
	// AdminUserRolesColumns holds the columns for the "admin_user_roles" table.
	AdminUserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "主键ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "user_id", Type: field.TypeInt64, Comment: "用户ID，关联 admin_users.id"},
		{Name: "role_id", Type: field.TypeInt64, Comment: "角色ID，关联 admin_roles.id"},
	}
	// AdminUserRolesTable holds the schema information for the "admin_user_roles" table.
	AdminUserRolesTable = &schema.Table{
		Name:       "admin_user_roles",
		Comment:    "用户角色关联表",
		Columns:    AdminUserRolesColumns,
		PrimaryKey: []*schema.Column{AdminUserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "admin_user_roles_admin_users_user",
				Columns:    []*schema.Column{AdminUserRolesColumns[3]},
				RefColumns: []*schema.Column{AdminUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "admin_user_roles_admin_roles_role",
				Columns:    []*schema.Column{AdminUserRolesColumns[4]},
				RefColumns: []*schema.Column{AdminRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "adminuserrole_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminUserRolesColumns[1]},
			},
			{
				Name:    "adminuserrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{AdminUserRolesColumns[3], AdminUserRolesColumns[4]},
			},
		},
	}
	// DepartmentsColumns holds the columns for the "departments" table.
	DepartmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "部门ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间，用于软删除"},
		{Name: "name", Type: field.TypeString, Comment: "部门名称"},
		{Name: "level", Type: field.TypeInt, Comment: "部门层级", Default: 1},
		{Name: "sort", Type: field.TypeInt, Comment: "排序", Default: 0},
		{Name: "is_active", Type: field.TypeBool, Comment: "是否启用", Default: true},
		{Name: "leader_id", Type: field.TypeInt64, Nullable: true, Comment: "部门负责人ID（管理员）"},
		{Name: "parent_id", Type: field.TypeInt64, Nullable: true, Comment: "父级部门ID"},
	}
	// DepartmentsTable holds the schema information for the "departments" table.
	DepartmentsTable = &schema.Table{
		Name:       "departments",
		Comment:    "部门表",
		Columns:    DepartmentsColumns,
		PrimaryKey: []*schema.Column{DepartmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "departments_departments_children",
				Columns:    []*schema.Column{DepartmentsColumns[9]},
				RefColumns: []*schema.Column{DepartmentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "department_created_at",
				Unique:  false,
				Columns: []*schema.Column{DepartmentsColumns[1]},
			},
			{
				Name:    "department_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{DepartmentsColumns[3]},
			},
		},
	}
	// TokenBlacklistsColumns holds the columns for the "token_blacklists" table.
	TokenBlacklistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "自增主键 ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "更新时间"},
		{Name: "token_hash", Type: field.TypeString, Unique: true, Size: 64, Comment: "JWT token 的 SHA256 哈希值，用于唯一索引"},
		{Name: "token", Type: field.TypeString, Nullable: true, Size: 4096, Comment: "完整的 JWT token 字符串（用于调试/日志）"},
		{Name: "expired_at", Type: field.TypeTime, Comment: "该 token 原本的过期时间，用于定时清理黑名单（过期后可删除）"},
	}
	// TokenBlacklistsTable holds the schema information for the "token_blacklists" table.
	TokenBlacklistsTable = &schema.Table{
		Name:       "token_blacklists",
		Comment:    "JWT Token 黑名单表，用于存储已注销或失效的 JWT token",
		Columns:    TokenBlacklistsColumns,
		PrimaryKey: []*schema.Column{TokenBlacklistsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tokenblacklist_created_at",
				Unique:  false,
				Columns: []*schema.Column{TokenBlacklistsColumns[1]},
			},
			{
				Name:    "tokenblacklist_token_hash",
				Unique:  true,
				Columns: []*schema.Column{TokenBlacklistsColumns[3]},
			},
			{
				Name:    "tokenblacklist_expired_at",
				Unique:  false,
				Columns: []*schema.Column{TokenBlacklistsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminPermissionsTable,
		AdminRolesTable,
		AdminRoleDeptsTable,
		AdminRolePermissionsTable,
		AdminUsersTable,
		AdminUserRolesTable,
		DepartmentsTable,
		TokenBlacklistsTable,
	}
)

func init() {
	AdminPermissionsTable.ForeignKeys[0].RefTable = AdminPermissionsTable
	AdminPermissionsTable.Annotation = &entsql.Annotation{
		Table: "admin_permissions",
	}
	AdminRolesTable.Annotation = &entsql.Annotation{
		Table: "admin_roles",
	}
	AdminRoleDeptsTable.Annotation = &entsql.Annotation{
		Table: "admin_role_depts",
	}
	AdminRolePermissionsTable.ForeignKeys[0].RefTable = AdminRolesTable
	AdminRolePermissionsTable.ForeignKeys[1].RefTable = AdminPermissionsTable
	AdminRolePermissionsTable.Annotation = &entsql.Annotation{
		Table: "admin_role_permissions",
	}
	AdminUsersTable.ForeignKeys[0].RefTable = DepartmentsTable
	AdminUsersTable.Annotation = &entsql.Annotation{
		Table: "admin_users",
	}
	AdminUsersTable.Annotation.Incremental = new(bool)
	*AdminUsersTable.Annotation.Incremental = true
	AdminUserRolesTable.ForeignKeys[0].RefTable = AdminUsersTable
	AdminUserRolesTable.ForeignKeys[1].RefTable = AdminRolesTable
	AdminUserRolesTable.Annotation = &entsql.Annotation{
		Table: "admin_user_roles",
	}
	DepartmentsTable.ForeignKeys[0].RefTable = DepartmentsTable
	DepartmentsTable.Annotation = &entsql.Annotation{
		Table: "departments",
	}
}
