// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/yuwen002/go-meteor-cms/api/cms/v1/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/forgot-password",
				Handler: forgotPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/register",
				Handler: registerAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/captcha",
				Handler: GetCaptchaHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/admin/admin-users",
					Handler: adminListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/admin-users/:id",
					Handler: adminDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/admin-users/:id",
					Handler: adminUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/admin/admin-users/create",
					Handler: adminCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/admin-users/me/change-password",
					Handler: changeMyPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/admin/admin-users/reset-password",
					Handler: resetAdminPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/admin/test-token",
					Handler: testTokenHandler(serverCtx),
				},
			}...,
		),
	)
}
