// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminDetailReq struct {
	ID int64 `path:"id"`
}

type AdminDetailResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	IsActive bool   `json:"is_active"`
}

type AdminItem struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Nickname    string `json:"nickname"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	Avatar      string `json:"avatar"`
	IsSuper     bool   `json:"isSuper"`
	IsActive    bool   `json:"isActive"`
	LastLoginAt string `json:"last_login_at"`
	CreatedAt   string `json:"createdAt"`
}

type AdminListReq struct {
	Page     int    `form:"page"`             // 页码
	PageSize int    `form:"page_size"`        // 每页数量
	Keyword  string `form:"keyword,optional"` // 搜索关键词（用户名/昵称/邮箱）
	Active   int    `form:"active,optional"`  // 可选：过滤启用状态
}

type AdminListResp struct {
	Total    int64       `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
	List     []AdminItem `json:"list"`
}

type CaptchaResp struct {
	CaptchaID     string `json:"captcha_id"`     // 验证码ID
	CaptchaBase64 string `json:"captcha_base64"` // 验证码图片base64
}

type ChangeMyPasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type CommonResp struct {
	ID      int64  `json:"id"`
	Message string `json:"message"`
}

type CreateAdminReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	IsActive bool   `json:"is_active"`
	IsSuper  bool   `json:"is_super"`
}

type ForgotPasswordReq struct {
	Username string `json:"username" validate:"required"` // 必填
}

type ForgotPasswordResp struct {
	Message string `json:"message"` // 返回提示
}

type LoginReq struct {
	Username  string `json:"username" validate:"required"`   // 必填
	Password  string `json:"password" validate:"required"`   // 必填
	CaptchaID string `json:"captcha_id" validate:"required"` // 验证码ID
	Captcha   string `json:"captcha" validate:"required"`    // 验证码
}

type LoginResp struct {
	Token string `json:"token"` // 登录成功返回 token
}

type RegisterReq struct {
	Username string `json:"username" validate:"required"`       // 必填
	Password string `json:"password" validate:"required,min=6"` // 必填，最少 6 位
	Email    string `json:"email" validate:"required,email"`    // 必填，格式必须是 email
	Nickname string `json:"nickname"`                           // 选填
}

type RegisterResp struct {
	Message string `json:"message"` // 注册成功提示
}

type ResetAdminPasswordReq struct {
	ID          int64  `json:"id"`
	NewPassword string `json:"new_password"`
}

type TestTokenResp struct {
	Message string                 `json:"message"`
	Claims  map[string]interface{} `json:"claims"`
}

type UpdateAdminReq struct {
	ID       int64  `path:"id"`
	Nickname string `json:"nickname,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	IsActive bool   `json:"is_active,optional"`
}
