// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ForgotPasswordReq struct {
	Username string `json:"username" validate:"required"` // 必填
}

type ForgotPasswordResp struct {
	Status  int    `json:"status"`  // 状态码（0 成功，1 失败）
	Message string `json:"message"` // 返回提示
}

type LoginReq struct {
	Username string `json:"username" validate:"required"` // 必填
	Password string `json:"password" validate:"required"` // 必填
}

type LoginResp struct {
	Token string `json:"token"` // 登录成功返回 token
}

type RegisterReq struct {
	Username string `json:"username" validate:"required"`       // 必填
	Password string `json:"password" validate:"required,min=6"` // 必填，最少 6 位
	Email    string `json:"email" validate:"required,email"`    // 必填，格式必须是 email
	Nickname string `json:"nickname"`                           // 选填
}

type RegisterResp struct {
	Message string `json:"message"` // 注册成功提示
}
