// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminBindDeptReq struct {
	Id     int64 `path:"id"`      // 管理员ID
	DeptId int64 `json:"dept_id"` // 部门ID
}

type AdminDetailReq struct {
	ID int64 `path:"id"`
}

type AdminDetailResp struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	IsActive bool   `json:"is_active"`
}

type AdminItem struct {
	Id          int64  `json:"id"`
	Username    string `json:"username"`
	Nickname    string `json:"nickname"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	Avatar      string `json:"avatar"`
	IsSuper     bool   `json:"isSuper"`
	IsActive    bool   `json:"isActive"`
	LastLoginAt string `json:"last_login_at"`
	CreatedAt   string `json:"createdAt"`
}

type AdminListReq struct {
	Page     int    `form:"page"`             // 页码
	PageSize int    `form:"page_size"`        // 每页数量
	Keyword  string `form:"keyword,optional"` // 搜索关键词（用户名/昵称/邮箱）
	Active   int    `form:"active,optional"`  // 可选：过滤启用状态
}

type AdminListResp struct {
	Total    int64       `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"page_size"`
	List     []AdminItem `json:"list"`
}

type CaptchaResp struct {
	CaptchaID     string `json:"captcha_id"`     // 验证码ID
	CaptchaBase64 string `json:"captcha_base64"` // 验证码图片base64
}

type ChangeMyPasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type CommonResp struct {
	ID      int64  `json:"id"`
	Message string `json:"message"`
}

type CreateAdminReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	IsActive bool   `json:"is_active"`
	IsSuper  bool   `json:"is_super"`
}

type DeleteAdminReq struct {
	Id int64 `path:"id"`
}

type DepartmentCreateReq struct {
	Name     string `json:"name"`      // 部门名称
	ParentId int64  `json:"parent_id"` // 父级部门ID
	Sort     int    `json:"sort"`      // 排序
	IsActive bool   `json:"is_active"` // 是否启用
	LeaderId int64  `json:"leader_id"` // 负责人ID
}

type DepartmentDeleteReq struct {
	Id int64 `path:"id"`
}

type DepartmentDetailReq struct {
	Id int64 `path:"id"`
}

type DepartmentDetailResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	ParentId int64  `json:"parent_id"`
	Sort     int    `json:"sort"`
	IsActive bool   `json:"is_active"`
	LeaderId int64  `json:"leader_id"`
}

type DepartmentTreeResp struct {
	Id       int64                `json:"id"`
	Name     string               `json:"name"`
	Sort     int                  `json:"sort"`
	IsActive bool                 `json:"is_active"`
	Children []DepartmentTreeResp `json:"children"`
}

type DepartmentUpdateReq struct {
	Id       int64  `path:"id"`
	Name     string `json:"name"`
	ParentId int64  `json:"parent_id"`
	Sort     int    `json:"sort"`
	IsActive bool   `json:"is_active"`
	LeaderId int64  `json:"leader_id"`
}

type DisableAdminReq struct {
	ID int64 `path:"id"`
}

type EnableAdminReq struct {
	ID int64 `path:"id"`
}

type ForgotPasswordReq struct {
	Username string `json:"username" validate:"required"` // 必填
}

type ForgotPasswordResp struct {
	Message string `json:"message"` // 返回提示
}

type LoginReq struct {
	Username  string `json:"username" validate:"required"`   // 必填
	Password  string `json:"password" validate:"required"`   // 必填
	CaptchaID string `json:"captcha_id" validate:"required"` // 验证码ID
	Captcha   string `json:"captcha" validate:"required"`    // 验证码
}

type LoginResp struct {
	Token string `json:"token"` // 登录成功返回 token
}

type PermissionItem struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required"`       // 必填
	Password string `json:"password" validate:"required,min=6"` // 必填，最少 6 位
	Email    string `json:"email" validate:"required,email"`    // 必填，格式必须是 email
	Nickname string `json:"nickname"`                           // 选填
}

type RegisterResp struct {
	Message string `json:"message"` // 注册成功提示
}

type ResetAdminPasswordReq struct {
	ID          int64  `json:"id"`
	NewPassword string `json:"new_password"`
}

type RoleCreateReq struct {
	Name      string `json:"name" validate:"required"` // 角色名称
	Code      string `json:"code" validate:"required"` // 角色编码
	Desc      string `json:"desc"`                     // 角色描述
	DataScope int    `json:"data_scope" default:"1"`   // 数据权限范围
	IsActive  bool   `json:"is_active" default:"true"` // 是否启用
	Sort      int    `json:"sort" default:"0"`         // 排序
}

type RoleDeleteReq struct {
	ID int64 `path:"id"`
}

type RoleDetailReq struct {
	ID int64 `path:"id"`
}

type RoleDetailResp struct {
	RoleItem
}

type RoleItem struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Code      string `json:"code"`
	Desc      string `json:"desc"`
	DataScope int    `json:"data_scope"`
	IsSystem  bool   `json:"is_system"`
	IsActive  bool   `json:"is_active"`
	Sort      int    `json:"sort"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RoleListReq struct {
	Page     int    `form:"page,default=1"`       // 页码
	PageSize int    `form:"page_size,default=20"` // 每页数量
	Keyword  string `form:"keyword,optional"`     // 搜索关键词（角色名称/编码）
	IsActive *bool  `form:"is_active,optional"`   // 是否启用
}

type RoleListResp struct {
	Total    int64      `json:"total"`
	Page     int        `json:"page"`
	PageSize int        `json:"page_size"`
	List     []RoleItem `json:"list"`
}

type RolePermissionAssignReq struct {
	RoleID        int64   `path:"id"`
	PermissionIDs []int64 `json:"permission_ids"` // 权限ID列表
}

type RolePermissionIDsResp struct {
	PermissionIDs []int64 `json:"permission_ids"`
}

type RolePermissionListResp struct {
	Permissions []PermissionItem `json:"permissions"`
}

type RoleUpdateReq struct {
	ID        int64   `path:"id"`
	Name      *string `json:"name,optional,options=nonzero"` // 角色名称，如果提供则不能为空
	Code      *string `json:"code,optional,options=nonzero"` // 角色编码，如果提供则不能为空
	Desc      *string `json:"desc,optional"`                 // 角色描述
	DataScope *int    `json:"data_scope,optional"`           // 数据权限范围
	IsActive  *bool   `json:"is_active,optional"`            // 是否启用
	Sort      *int    `json:"sort,optional"`                 // 排序
}

type TestTokenResp struct {
	Message string                 `json:"message"`
	Claims  map[string]interface{} `json:"claims"`
}

type UpdateAdminReq struct {
	ID       int64  `path:"id"`
	Nickname string `json:"nickname,optional"`
	Email    string `json:"email,optional"`
	Phone    string `json:"phone,optional"`
	IsActive bool   `json:"is_active,optional"`
}
