// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yuwen002/go-meteor-cms/ent/adminpermission"
)

// 后台权限表（菜单/按钮/接口）
type AdminPermission struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 权限名称，如 用户管理 / 新增用户
	Name string `json:"name,omitempty"`
	// 父级ID（用于菜单树）
	ParentID *int64 `json:"parent_id,omitempty"`
	// 权限类型：1 菜单 2 按钮 3 API
	Type int `json:"type,omitempty"`
	// 前端路由路径，仅菜单(type=1)使用
	Path string `json:"path,omitempty"`
	// 前端组件路径，如 views/user/list.vue
	Component string `json:"component,omitempty"`
	// 菜单图标
	Icon string `json:"icon,omitempty"`
	// API 方法：GET/POST/PUT/DELETE，仅 type=3 使用
	Method string `json:"method,omitempty"`
	// API 路径，如 /admin/user/list，仅 type=3 使用
	APIPath string `json:"api_path,omitempty"`
	// 权限标识，如 system:user:list
	Permission string `json:"permission,omitempty"`
	// 是否启用
	IsActive bool `json:"is_active,omitempty"`
	// 排序
	Sort int `json:"sort,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminPermissionQuery when eager-loading is set.
	Edges        AdminPermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdminPermissionEdges holds the relations/edges for other nodes in the graph.
type AdminPermissionEdges struct {
	// Parent holds the value of the parent edge.
	Parent *AdminPermission `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*AdminPermission `json:"children,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminPermissionEdges) ParentOrErr() (*AdminPermission, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: adminpermission.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e AdminPermissionEdges) ChildrenOrErr() ([]*AdminPermission, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminpermission.FieldIsActive:
			values[i] = new(sql.NullBool)
		case adminpermission.FieldID, adminpermission.FieldParentID, adminpermission.FieldType, adminpermission.FieldSort:
			values[i] = new(sql.NullInt64)
		case adminpermission.FieldName, adminpermission.FieldPath, adminpermission.FieldComponent, adminpermission.FieldIcon, adminpermission.FieldMethod, adminpermission.FieldAPIPath, adminpermission.FieldPermission:
			values[i] = new(sql.NullString)
		case adminpermission.FieldCreatedAt, adminpermission.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminPermission fields.
func (_m *AdminPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminpermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminpermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adminpermission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adminpermission.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case adminpermission.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = new(int64)
				*_m.ParentID = value.Int64
			}
		case adminpermission.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = int(value.Int64)
			}
		case adminpermission.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case adminpermission.FieldComponent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field component", values[i])
			} else if value.Valid {
				_m.Component = value.String
			}
		case adminpermission.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case adminpermission.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case adminpermission.FieldAPIPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_path", values[i])
			} else if value.Valid {
				_m.APIPath = value.String
			}
		case adminpermission.FieldPermission:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission", values[i])
			} else if value.Valid {
				_m.Permission = value.String
			}
		case adminpermission.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case adminpermission.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminPermission.
// This includes values selected through modifiers, order, etc.
func (_m *AdminPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the AdminPermission entity.
func (_m *AdminPermission) QueryParent() *AdminPermissionQuery {
	return NewAdminPermissionClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the AdminPermission entity.
func (_m *AdminPermission) QueryChildren() *AdminPermissionQuery {
	return NewAdminPermissionClient(_m.config).QueryChildren(_m)
}

// Update returns a builder for updating this AdminPermission.
// Note that you need to call AdminPermission.Unwrap() before calling this method if this AdminPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminPermission) Update() *AdminPermissionUpdateOne {
	return NewAdminPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminPermission) Unwrap() *AdminPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminPermission) String() string {
	var builder strings.Builder
	builder.WriteString("AdminPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.ParentID; v != nil {
		builder.WriteString("parent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("component=")
	builder.WriteString(_m.Component)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("api_path=")
	builder.WriteString(_m.APIPath)
	builder.WriteString(", ")
	builder.WriteString("permission=")
	builder.WriteString(_m.Permission)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteByte(')')
	return builder.String()
}

// AdminPermissions is a parsable slice of AdminPermission.
type AdminPermissions []*AdminPermission
