// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminpermission"
	"github.com/yuwen002/go-meteor-cms/ent/adminrole"
	"github.com/yuwen002/go-meteor-cms/ent/adminrolepermission"
	"github.com/yuwen002/go-meteor-cms/ent/predicate"
)

// AdminRolePermissionQuery is the builder for querying AdminRolePermission entities.
type AdminRolePermissionQuery struct {
	config
	ctx            *QueryContext
	order          []adminrolepermission.OrderOption
	inters         []Interceptor
	predicates     []predicate.AdminRolePermission
	withRole       *AdminRoleQuery
	withPermission *AdminPermissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminRolePermissionQuery builder.
func (_q *AdminRolePermissionQuery) Where(ps ...predicate.AdminRolePermission) *AdminRolePermissionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AdminRolePermissionQuery) Limit(limit int) *AdminRolePermissionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AdminRolePermissionQuery) Offset(offset int) *AdminRolePermissionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AdminRolePermissionQuery) Unique(unique bool) *AdminRolePermissionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AdminRolePermissionQuery) Order(o ...adminrolepermission.OrderOption) *AdminRolePermissionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRole chains the current query on the "role" edge.
func (_q *AdminRolePermissionQuery) QueryRole() *AdminRoleQuery {
	query := (&AdminRoleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminrolepermission.Table, adminrolepermission.FieldID, selector),
			sqlgraph.To(adminrole.Table, adminrole.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, adminrolepermission.RoleTable, adminrolepermission.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPermission chains the current query on the "permission" edge.
func (_q *AdminRolePermissionQuery) QueryPermission() *AdminPermissionQuery {
	query := (&AdminPermissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminrolepermission.Table, adminrolepermission.FieldID, selector),
			sqlgraph.To(adminpermission.Table, adminpermission.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, adminrolepermission.PermissionTable, adminrolepermission.PermissionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdminRolePermission entity from the query.
// Returns a *NotFoundError when no AdminRolePermission was found.
func (_q *AdminRolePermissionQuery) First(ctx context.Context) (*AdminRolePermission, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminrolepermission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) FirstX(ctx context.Context) *AdminRolePermission {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminRolePermission ID from the query.
// Returns a *NotFoundError when no AdminRolePermission ID was found.
func (_q *AdminRolePermissionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminrolepermission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminRolePermission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminRolePermission entity is found.
// Returns a *NotFoundError when no AdminRolePermission entities are found.
func (_q *AdminRolePermissionQuery) Only(ctx context.Context) (*AdminRolePermission, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminrolepermission.Label}
	default:
		return nil, &NotSingularError{adminrolepermission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) OnlyX(ctx context.Context) *AdminRolePermission {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminRolePermission ID in the query.
// Returns a *NotSingularError when more than one AdminRolePermission ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AdminRolePermissionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminrolepermission.Label}
	default:
		err = &NotSingularError{adminrolepermission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminRolePermissions.
func (_q *AdminRolePermissionQuery) All(ctx context.Context) ([]*AdminRolePermission, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminRolePermission, *AdminRolePermissionQuery]()
	return withInterceptors[[]*AdminRolePermission](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) AllX(ctx context.Context) []*AdminRolePermission {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminRolePermission IDs.
func (_q *AdminRolePermissionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(adminrolepermission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AdminRolePermissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AdminRolePermissionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AdminRolePermissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AdminRolePermissionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminRolePermissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AdminRolePermissionQuery) Clone() *AdminRolePermissionQuery {
	if _q == nil {
		return nil
	}
	return &AdminRolePermissionQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]adminrolepermission.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.AdminRolePermission{}, _q.predicates...),
		withRole:       _q.withRole.Clone(),
		withPermission: _q.withPermission.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdminRolePermissionQuery) WithRole(opts ...func(*AdminRoleQuery)) *AdminRolePermissionQuery {
	query := (&AdminRoleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRole = query
	return _q
}

// WithPermission tells the query-builder to eager-load the nodes that are connected to
// the "permission" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AdminRolePermissionQuery) WithPermission(opts ...func(*AdminPermissionQuery)) *AdminRolePermissionQuery {
	query := (&AdminPermissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPermission = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdminRolePermission.Query().
//		GroupBy(adminrolepermission.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AdminRolePermissionQuery) GroupBy(field string, fields ...string) *AdminRolePermissionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminRolePermissionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = adminrolepermission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.AdminRolePermission.Query().
//		Select(adminrolepermission.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AdminRolePermissionQuery) Select(fields ...string) *AdminRolePermissionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AdminRolePermissionSelect{AdminRolePermissionQuery: _q}
	sbuild.label = adminrolepermission.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminRolePermissionSelect configured with the given aggregations.
func (_q *AdminRolePermissionQuery) Aggregate(fns ...AggregateFunc) *AdminRolePermissionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AdminRolePermissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !adminrolepermission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AdminRolePermissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminRolePermission, error) {
	var (
		nodes       = []*AdminRolePermission{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withRole != nil,
			_q.withPermission != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminRolePermission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminRolePermission{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRole; query != nil {
		if err := _q.loadRole(ctx, query, nodes, nil,
			func(n *AdminRolePermission, e *AdminRole) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPermission; query != nil {
		if err := _q.loadPermission(ctx, query, nodes, nil,
			func(n *AdminRolePermission, e *AdminPermission) { n.Edges.Permission = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AdminRolePermissionQuery) loadRole(ctx context.Context, query *AdminRoleQuery, nodes []*AdminRolePermission, init func(*AdminRolePermission), assign func(*AdminRolePermission, *AdminRole)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AdminRolePermission)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminrole.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AdminRolePermissionQuery) loadPermission(ctx context.Context, query *AdminPermissionQuery, nodes []*AdminRolePermission, init func(*AdminRolePermission), assign func(*AdminRolePermission, *AdminPermission)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*AdminRolePermission)
	for i := range nodes {
		fk := nodes[i].PermissionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminpermission.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "permission_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *AdminRolePermissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AdminRolePermissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminrolepermission.Table, adminrolepermission.Columns, sqlgraph.NewFieldSpec(adminrolepermission.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminrolepermission.FieldID)
		for i := range fields {
			if fields[i] != adminrolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRole != nil {
			_spec.Node.AddColumnOnce(adminrolepermission.FieldRoleID)
		}
		if _q.withPermission != nil {
			_spec.Node.AddColumnOnce(adminrolepermission.FieldPermissionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AdminRolePermissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(adminrolepermission.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = adminrolepermission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminRolePermissionGroupBy is the group-by builder for AdminRolePermission entities.
type AdminRolePermissionGroupBy struct {
	selector
	build *AdminRolePermissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AdminRolePermissionGroupBy) Aggregate(fns ...AggregateFunc) *AdminRolePermissionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AdminRolePermissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminRolePermissionQuery, *AdminRolePermissionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AdminRolePermissionGroupBy) sqlScan(ctx context.Context, root *AdminRolePermissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminRolePermissionSelect is the builder for selecting fields of AdminRolePermission entities.
type AdminRolePermissionSelect struct {
	*AdminRolePermissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AdminRolePermissionSelect) Aggregate(fns ...AggregateFunc) *AdminRolePermissionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AdminRolePermissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminRolePermissionQuery, *AdminRolePermissionSelect](ctx, _s.AdminRolePermissionQuery, _s, _s.inters, v)
}

func (_s *AdminRolePermissionSelect) sqlScan(ctx context.Context, root *AdminRolePermissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
