// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminuser"
	"github.com/yuwen002/go-meteor-cms/ent/department"
	"github.com/yuwen002/go-meteor-cms/ent/predicate"
)

// AdminUserUpdate is the builder for updating AdminUser entities.
type AdminUserUpdate struct {
	config
	hooks    []Hook
	mutation *AdminUserMutation
}

// Where appends a list predicates to the AdminUserUpdate builder.
func (_u *AdminUserUpdate) Where(ps ...predicate.AdminUser) *AdminUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminUserUpdate) SetCreatedAt(v time.Time) *AdminUserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableCreatedAt(v *time.Time) *AdminUserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminUserUpdate) SetUpdatedAt(v time.Time) *AdminUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminUserUpdate) SetDeletedAt(v time.Time) *AdminUserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableDeletedAt(v *time.Time) *AdminUserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminUserUpdate) ClearDeletedAt() *AdminUserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUsername sets the "username" field.
func (_u *AdminUserUpdate) SetUsername(v string) *AdminUserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableUsername(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AdminUserUpdate) SetPasswordHash(v string) *AdminUserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillablePasswordHash(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *AdminUserUpdate) SetNickname(v string) *AdminUserUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableNickname(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// ClearNickname clears the value of the "nickname" field.
func (_u *AdminUserUpdate) ClearNickname() *AdminUserUpdate {
	_u.mutation.ClearNickname()
	return _u
}

// SetEmail sets the "email" field.
func (_u *AdminUserUpdate) SetEmail(v string) *AdminUserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableEmail(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *AdminUserUpdate) ClearEmail() *AdminUserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *AdminUserUpdate) SetPhone(v string) *AdminUserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillablePhone(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *AdminUserUpdate) ClearPhone() *AdminUserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *AdminUserUpdate) SetAvatar(v string) *AdminUserUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableAvatar(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// SetDeptID sets the "dept_id" field.
func (_u *AdminUserUpdate) SetDeptID(v int64) *AdminUserUpdate {
	_u.mutation.SetDeptID(v)
	return _u
}

// SetNillableDeptID sets the "dept_id" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableDeptID(v *int64) *AdminUserUpdate {
	if v != nil {
		_u.SetDeptID(*v)
	}
	return _u
}

// ClearDeptID clears the value of the "dept_id" field.
func (_u *AdminUserUpdate) ClearDeptID() *AdminUserUpdate {
	_u.mutation.ClearDeptID()
	return _u
}

// SetIsSuper sets the "is_super" field.
func (_u *AdminUserUpdate) SetIsSuper(v bool) *AdminUserUpdate {
	_u.mutation.SetIsSuper(v)
	return _u
}

// SetNillableIsSuper sets the "is_super" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableIsSuper(v *bool) *AdminUserUpdate {
	if v != nil {
		_u.SetIsSuper(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminUserUpdate) SetIsActive(v bool) *AdminUserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableIsActive(v *bool) *AdminUserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *AdminUserUpdate) SetLastLoginAt(v time.Time) *AdminUserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableLastLoginAt(v *time.Time) *AdminUserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *AdminUserUpdate) ClearLastLoginAt() *AdminUserUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetResetToken sets the "reset_token" field.
func (_u *AdminUserUpdate) SetResetToken(v string) *AdminUserUpdate {
	_u.mutation.SetResetToken(v)
	return _u
}

// SetNillableResetToken sets the "reset_token" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableResetToken(v *string) *AdminUserUpdate {
	if v != nil {
		_u.SetResetToken(*v)
	}
	return _u
}

// ClearResetToken clears the value of the "reset_token" field.
func (_u *AdminUserUpdate) ClearResetToken() *AdminUserUpdate {
	_u.mutation.ClearResetToken()
	return _u
}

// SetResetExpire sets the "reset_expire" field.
func (_u *AdminUserUpdate) SetResetExpire(v time.Time) *AdminUserUpdate {
	_u.mutation.SetResetExpire(v)
	return _u
}

// SetNillableResetExpire sets the "reset_expire" field if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableResetExpire(v *time.Time) *AdminUserUpdate {
	if v != nil {
		_u.SetResetExpire(*v)
	}
	return _u
}

// ClearResetExpire clears the value of the "reset_expire" field.
func (_u *AdminUserUpdate) ClearResetExpire() *AdminUserUpdate {
	_u.mutation.ClearResetExpire()
	return _u
}

// SetDepartmentID sets the "department" edge to the Department entity by ID.
func (_u *AdminUserUpdate) SetDepartmentID(id int64) *AdminUserUpdate {
	_u.mutation.SetDepartmentID(id)
	return _u
}

// SetNillableDepartmentID sets the "department" edge to the Department entity by ID if the given value is not nil.
func (_u *AdminUserUpdate) SetNillableDepartmentID(id *int64) *AdminUserUpdate {
	if id != nil {
		_u = _u.SetDepartmentID(*id)
	}
	return _u
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *AdminUserUpdate) SetDepartment(v *Department) *AdminUserUpdate {
	return _u.SetDepartmentID(v.ID)
}

// Mutation returns the AdminUserMutation object of the builder.
func (_u *AdminUserUpdate) Mutation() *AdminUserMutation {
	return _u.mutation
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *AdminUserUpdate) ClearDepartment() *AdminUserUpdate {
	_u.mutation.ClearDepartment()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminUserUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminUserUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if adminuser.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminuser.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adminuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := adminuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AdminUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := adminuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "AdminUser.password_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminuser.Table, adminuser.Columns, sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminuser.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(adminuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(adminuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(adminuser.FieldNickname, field.TypeString, value)
	}
	if _u.mutation.NicknameCleared() {
		_spec.ClearField(adminuser.FieldNickname, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(adminuser.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(adminuser.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(adminuser.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(adminuser.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(adminuser.FieldAvatar, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSuper(); ok {
		_spec.SetField(adminuser.FieldIsSuper, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminuser.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(adminuser.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(adminuser.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResetToken(); ok {
		_spec.SetField(adminuser.FieldResetToken, field.TypeString, value)
	}
	if _u.mutation.ResetTokenCleared() {
		_spec.ClearField(adminuser.FieldResetToken, field.TypeString)
	}
	if value, ok := _u.mutation.ResetExpire(); ok {
		_spec.SetField(adminuser.FieldResetExpire, field.TypeTime, value)
	}
	if _u.mutation.ResetExpireCleared() {
		_spec.ClearField(adminuser.FieldResetExpire, field.TypeTime)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminuser.DepartmentTable,
			Columns: []string{adminuser.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminuser.DepartmentTable,
			Columns: []string{adminuser.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminUserUpdateOne is the builder for updating a single AdminUser entity.
type AdminUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminUserMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminUserUpdateOne) SetCreatedAt(v time.Time) *AdminUserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableCreatedAt(v *time.Time) *AdminUserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminUserUpdateOne) SetUpdatedAt(v time.Time) *AdminUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminUserUpdateOne) SetDeletedAt(v time.Time) *AdminUserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableDeletedAt(v *time.Time) *AdminUserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminUserUpdateOne) ClearDeletedAt() *AdminUserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUsername sets the "username" field.
func (_u *AdminUserUpdateOne) SetUsername(v string) *AdminUserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableUsername(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AdminUserUpdateOne) SetPasswordHash(v string) *AdminUserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillablePasswordHash(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *AdminUserUpdateOne) SetNickname(v string) *AdminUserUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableNickname(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// ClearNickname clears the value of the "nickname" field.
func (_u *AdminUserUpdateOne) ClearNickname() *AdminUserUpdateOne {
	_u.mutation.ClearNickname()
	return _u
}

// SetEmail sets the "email" field.
func (_u *AdminUserUpdateOne) SetEmail(v string) *AdminUserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableEmail(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *AdminUserUpdateOne) ClearEmail() *AdminUserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *AdminUserUpdateOne) SetPhone(v string) *AdminUserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillablePhone(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *AdminUserUpdateOne) ClearPhone() *AdminUserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *AdminUserUpdateOne) SetAvatar(v string) *AdminUserUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableAvatar(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// SetDeptID sets the "dept_id" field.
func (_u *AdminUserUpdateOne) SetDeptID(v int64) *AdminUserUpdateOne {
	_u.mutation.SetDeptID(v)
	return _u
}

// SetNillableDeptID sets the "dept_id" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableDeptID(v *int64) *AdminUserUpdateOne {
	if v != nil {
		_u.SetDeptID(*v)
	}
	return _u
}

// ClearDeptID clears the value of the "dept_id" field.
func (_u *AdminUserUpdateOne) ClearDeptID() *AdminUserUpdateOne {
	_u.mutation.ClearDeptID()
	return _u
}

// SetIsSuper sets the "is_super" field.
func (_u *AdminUserUpdateOne) SetIsSuper(v bool) *AdminUserUpdateOne {
	_u.mutation.SetIsSuper(v)
	return _u
}

// SetNillableIsSuper sets the "is_super" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableIsSuper(v *bool) *AdminUserUpdateOne {
	if v != nil {
		_u.SetIsSuper(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminUserUpdateOne) SetIsActive(v bool) *AdminUserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableIsActive(v *bool) *AdminUserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *AdminUserUpdateOne) SetLastLoginAt(v time.Time) *AdminUserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableLastLoginAt(v *time.Time) *AdminUserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *AdminUserUpdateOne) ClearLastLoginAt() *AdminUserUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// SetResetToken sets the "reset_token" field.
func (_u *AdminUserUpdateOne) SetResetToken(v string) *AdminUserUpdateOne {
	_u.mutation.SetResetToken(v)
	return _u
}

// SetNillableResetToken sets the "reset_token" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableResetToken(v *string) *AdminUserUpdateOne {
	if v != nil {
		_u.SetResetToken(*v)
	}
	return _u
}

// ClearResetToken clears the value of the "reset_token" field.
func (_u *AdminUserUpdateOne) ClearResetToken() *AdminUserUpdateOne {
	_u.mutation.ClearResetToken()
	return _u
}

// SetResetExpire sets the "reset_expire" field.
func (_u *AdminUserUpdateOne) SetResetExpire(v time.Time) *AdminUserUpdateOne {
	_u.mutation.SetResetExpire(v)
	return _u
}

// SetNillableResetExpire sets the "reset_expire" field if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableResetExpire(v *time.Time) *AdminUserUpdateOne {
	if v != nil {
		_u.SetResetExpire(*v)
	}
	return _u
}

// ClearResetExpire clears the value of the "reset_expire" field.
func (_u *AdminUserUpdateOne) ClearResetExpire() *AdminUserUpdateOne {
	_u.mutation.ClearResetExpire()
	return _u
}

// SetDepartmentID sets the "department" edge to the Department entity by ID.
func (_u *AdminUserUpdateOne) SetDepartmentID(id int64) *AdminUserUpdateOne {
	_u.mutation.SetDepartmentID(id)
	return _u
}

// SetNillableDepartmentID sets the "department" edge to the Department entity by ID if the given value is not nil.
func (_u *AdminUserUpdateOne) SetNillableDepartmentID(id *int64) *AdminUserUpdateOne {
	if id != nil {
		_u = _u.SetDepartmentID(*id)
	}
	return _u
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *AdminUserUpdateOne) SetDepartment(v *Department) *AdminUserUpdateOne {
	return _u.SetDepartmentID(v.ID)
}

// Mutation returns the AdminUserMutation object of the builder.
func (_u *AdminUserUpdateOne) Mutation() *AdminUserMutation {
	return _u.mutation
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *AdminUserUpdateOne) ClearDepartment() *AdminUserUpdateOne {
	_u.mutation.ClearDepartment()
	return _u
}

// Where appends a list predicates to the AdminUserUpdate builder.
func (_u *AdminUserUpdateOne) Where(ps ...predicate.AdminUser) *AdminUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminUserUpdateOne) Select(field string, fields ...string) *AdminUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminUser entity.
func (_u *AdminUserUpdateOne) Save(ctx context.Context) (*AdminUser, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserUpdateOne) SaveX(ctx context.Context) *AdminUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminUserUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if adminuser.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminuser.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adminuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := adminuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AdminUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := adminuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "AdminUser.password_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUserUpdateOne) sqlSave(ctx context.Context) (_node *AdminUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminuser.Table, adminuser.Columns, sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminuser.FieldID)
		for _, f := range fields {
			if !adminuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminuser.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(adminuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(adminuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(adminuser.FieldNickname, field.TypeString, value)
	}
	if _u.mutation.NicknameCleared() {
		_spec.ClearField(adminuser.FieldNickname, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(adminuser.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(adminuser.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(adminuser.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(adminuser.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(adminuser.FieldAvatar, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSuper(); ok {
		_spec.SetField(adminuser.FieldIsSuper, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminuser.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(adminuser.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(adminuser.FieldLastLoginAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResetToken(); ok {
		_spec.SetField(adminuser.FieldResetToken, field.TypeString, value)
	}
	if _u.mutation.ResetTokenCleared() {
		_spec.ClearField(adminuser.FieldResetToken, field.TypeString)
	}
	if value, ok := _u.mutation.ResetExpire(); ok {
		_spec.SetField(adminuser.FieldResetExpire, field.TypeTime, value)
	}
	if _u.mutation.ResetExpireCleared() {
		_spec.ClearField(adminuser.FieldResetExpire, field.TypeTime)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminuser.DepartmentTable,
			Columns: []string{adminuser.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminuser.DepartmentTable,
			Columns: []string{adminuser.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdminUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
