// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yuwen002/go-meteor-cms/ent/adminrole"
)

// 后台角色表
type AdminRole struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID，自增
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间，用于软删除
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 角色名称
	Name string `json:"name,omitempty"`
	// 角色编码，用于系统标识，如 SUPER_ADMIN
	Code string `json:"code,omitempty"`
	// 角色描述
	Desc string `json:"desc,omitempty"`
	// 数据权限范围：1 全公司 / 2 本部门 / 3 部门及子部门 / 4 仅自己 / 5 自定义部门
	DataScope int `json:"data_scope,omitempty"`
	// 是否系统内置角色（禁止删除）
	IsSystem bool `json:"is_system,omitempty"`
	// 是否启用
	IsActive bool `json:"is_active,omitempty"`
	// 排序，从小到大
	Sort int `json:"sort,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminRoleQuery when eager-loading is set.
	Edges        AdminRoleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdminRoleEdges holds the relations/edges for other nodes in the graph.
type AdminRoleEdges struct {
	// Permissions holds the value of the permissions edge.
	Permissions []*AdminPermission `json:"permissions,omitempty"`
	// Users holds the value of the users edge.
	Users []*AdminUser `json:"users,omitempty"`
	// RolePermissions holds the value of the role_permissions edge.
	RolePermissions []*AdminRolePermission `json:"role_permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PermissionsOrErr returns the Permissions value or an error if the edge
// was not loaded in eager-loading.
func (e AdminRoleEdges) PermissionsOrErr() ([]*AdminPermission, error) {
	if e.loadedTypes[0] {
		return e.Permissions, nil
	}
	return nil, &NotLoadedError{edge: "permissions"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e AdminRoleEdges) UsersOrErr() ([]*AdminUser, error) {
	if e.loadedTypes[1] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// RolePermissionsOrErr returns the RolePermissions value or an error if the edge
// was not loaded in eager-loading.
func (e AdminRoleEdges) RolePermissionsOrErr() ([]*AdminRolePermission, error) {
	if e.loadedTypes[2] {
		return e.RolePermissions, nil
	}
	return nil, &NotLoadedError{edge: "role_permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminRole) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminrole.FieldIsSystem, adminrole.FieldIsActive:
			values[i] = new(sql.NullBool)
		case adminrole.FieldID, adminrole.FieldDataScope, adminrole.FieldSort:
			values[i] = new(sql.NullInt64)
		case adminrole.FieldName, adminrole.FieldCode, adminrole.FieldDesc:
			values[i] = new(sql.NullString)
		case adminrole.FieldCreatedAt, adminrole.FieldUpdatedAt, adminrole.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminRole fields.
func (_m *AdminRole) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminrole.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminrole.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adminrole.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adminrole.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case adminrole.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case adminrole.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case adminrole.FieldDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desc", values[i])
			} else if value.Valid {
				_m.Desc = value.String
			}
		case adminrole.FieldDataScope:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field data_scope", values[i])
			} else if value.Valid {
				_m.DataScope = int(value.Int64)
			}
		case adminrole.FieldIsSystem:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system", values[i])
			} else if value.Valid {
				_m.IsSystem = value.Bool
			}
		case adminrole.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case adminrole.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminRole.
// This includes values selected through modifiers, order, etc.
func (_m *AdminRole) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPermissions queries the "permissions" edge of the AdminRole entity.
func (_m *AdminRole) QueryPermissions() *AdminPermissionQuery {
	return NewAdminRoleClient(_m.config).QueryPermissions(_m)
}

// QueryUsers queries the "users" edge of the AdminRole entity.
func (_m *AdminRole) QueryUsers() *AdminUserQuery {
	return NewAdminRoleClient(_m.config).QueryUsers(_m)
}

// QueryRolePermissions queries the "role_permissions" edge of the AdminRole entity.
func (_m *AdminRole) QueryRolePermissions() *AdminRolePermissionQuery {
	return NewAdminRoleClient(_m.config).QueryRolePermissions(_m)
}

// Update returns a builder for updating this AdminRole.
// Note that you need to call AdminRole.Unwrap() before calling this method if this AdminRole
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminRole) Update() *AdminRoleUpdateOne {
	return NewAdminRoleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminRole entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminRole) Unwrap() *AdminRole {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminRole is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminRole) String() string {
	var builder strings.Builder
	builder.WriteString("AdminRole(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("desc=")
	builder.WriteString(_m.Desc)
	builder.WriteString(", ")
	builder.WriteString("data_scope=")
	builder.WriteString(fmt.Sprintf("%v", _m.DataScope))
	builder.WriteString(", ")
	builder.WriteString("is_system=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSystem))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteByte(')')
	return builder.String()
}

// AdminRoles is a parsable slice of AdminRole.
type AdminRoles []*AdminRole
