// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminuserrole"
	"github.com/yuwen002/go-meteor-cms/ent/predicate"
)

// AdminUserRoleUpdate is the builder for updating AdminUserRole entities.
type AdminUserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *AdminUserRoleMutation
}

// Where appends a list predicates to the AdminUserRoleUpdate builder.
func (_u *AdminUserRoleUpdate) Where(ps ...predicate.AdminUserRole) *AdminUserRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminUserRoleUpdate) SetCreatedAt(v time.Time) *AdminUserRoleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableCreatedAt(v *time.Time) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminUserRoleUpdate) SetUpdatedAt(v time.Time) *AdminUserRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminUserRoleUpdate) SetDeletedAt(v time.Time) *AdminUserRoleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableDeletedAt(v *time.Time) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminUserRoleUpdate) ClearDeletedAt() *AdminUserRoleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdminUserRoleUpdate) SetUserID(v int64) *AdminUserRoleUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableUserID(v *int64) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AdminUserRoleUpdate) AddUserID(v int64) *AdminUserRoleUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *AdminUserRoleUpdate) SetRoleID(v int64) *AdminUserRoleUpdate {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableRoleID(v *int64) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *AdminUserRoleUpdate) AddRoleID(v int64) *AdminUserRoleUpdate {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetDummy sets the "dummy" field.
func (_u *AdminUserRoleUpdate) SetDummy(v uint8) *AdminUserRoleUpdate {
	_u.mutation.ResetDummy()
	_u.mutation.SetDummy(v)
	return _u
}

// SetNillableDummy sets the "dummy" field if the given value is not nil.
func (_u *AdminUserRoleUpdate) SetNillableDummy(v *uint8) *AdminUserRoleUpdate {
	if v != nil {
		_u.SetDummy(*v)
	}
	return _u
}

// AddDummy adds value to the "dummy" field.
func (_u *AdminUserRoleUpdate) AddDummy(v int8) *AdminUserRoleUpdate {
	_u.mutation.AddDummy(v)
	return _u
}

// Mutation returns the AdminUserRoleMutation object of the builder.
func (_u *AdminUserRoleUpdate) Mutation() *AdminUserRoleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminUserRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminUserRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminUserRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminuserrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUserRoleUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := adminuserrole.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserRole.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleID(); ok {
		if err := adminuserrole.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserRole.role_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUserRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminuserrole.Table, adminuserrole.Columns, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminuserrole.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminuserrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminuserrole.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminuserrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(adminuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(adminuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(adminuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(adminuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Dummy(); ok {
		_spec.SetField(adminuserrole.FieldDummy, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedDummy(); ok {
		_spec.AddField(adminuserrole.FieldDummy, field.TypeUint8, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminUserRoleUpdateOne is the builder for updating a single AdminUserRole entity.
type AdminUserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminUserRoleMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminUserRoleUpdateOne) SetCreatedAt(v time.Time) *AdminUserRoleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableCreatedAt(v *time.Time) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminUserRoleUpdateOne) SetUpdatedAt(v time.Time) *AdminUserRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminUserRoleUpdateOne) SetDeletedAt(v time.Time) *AdminUserRoleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableDeletedAt(v *time.Time) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminUserRoleUpdateOne) ClearDeletedAt() *AdminUserRoleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AdminUserRoleUpdateOne) SetUserID(v int64) *AdminUserRoleUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableUserID(v *int64) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AdminUserRoleUpdateOne) AddUserID(v int64) *AdminUserRoleUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *AdminUserRoleUpdateOne) SetRoleID(v int64) *AdminUserRoleUpdateOne {
	_u.mutation.ResetRoleID()
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableRoleID(v *int64) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// AddRoleID adds value to the "role_id" field.
func (_u *AdminUserRoleUpdateOne) AddRoleID(v int64) *AdminUserRoleUpdateOne {
	_u.mutation.AddRoleID(v)
	return _u
}

// SetDummy sets the "dummy" field.
func (_u *AdminUserRoleUpdateOne) SetDummy(v uint8) *AdminUserRoleUpdateOne {
	_u.mutation.ResetDummy()
	_u.mutation.SetDummy(v)
	return _u
}

// SetNillableDummy sets the "dummy" field if the given value is not nil.
func (_u *AdminUserRoleUpdateOne) SetNillableDummy(v *uint8) *AdminUserRoleUpdateOne {
	if v != nil {
		_u.SetDummy(*v)
	}
	return _u
}

// AddDummy adds value to the "dummy" field.
func (_u *AdminUserRoleUpdateOne) AddDummy(v int8) *AdminUserRoleUpdateOne {
	_u.mutation.AddDummy(v)
	return _u
}

// Mutation returns the AdminUserRoleMutation object of the builder.
func (_u *AdminUserRoleUpdateOne) Mutation() *AdminUserRoleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminUserRoleUpdate builder.
func (_u *AdminUserRoleUpdateOne) Where(ps ...predicate.AdminUserRole) *AdminUserRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminUserRoleUpdateOne) Select(field string, fields ...string) *AdminUserRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminUserRole entity.
func (_u *AdminUserRoleUpdateOne) Save(ctx context.Context) (*AdminUserRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminUserRoleUpdateOne) SaveX(ctx context.Context) *AdminUserRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminUserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminUserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminUserRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminuserrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminUserRoleUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := adminuserrole.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserRole.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RoleID(); ok {
		if err := adminuserrole.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "AdminUserRole.role_id": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminUserRoleUpdateOne) sqlSave(ctx context.Context) (_node *AdminUserRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminuserrole.Table, adminuserrole.Columns, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminUserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminuserrole.FieldID)
		for _, f := range fields {
			if !adminuserrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminuserrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminuserrole.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminuserrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminuserrole.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminuserrole.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(adminuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(adminuserrole.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RoleID(); ok {
		_spec.SetField(adminuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRoleID(); ok {
		_spec.AddField(adminuserrole.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Dummy(); ok {
		_spec.SetField(adminuserrole.FieldDummy, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedDummy(); ok {
		_spec.AddField(adminuserrole.FieldDummy, field.TypeUint8, value)
	}
	_node = &AdminUserRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminuserrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
