// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminrole"
	"github.com/yuwen002/go-meteor-cms/ent/predicate"
)

// AdminRoleUpdate is the builder for updating AdminRole entities.
type AdminRoleUpdate struct {
	config
	hooks    []Hook
	mutation *AdminRoleMutation
}

// Where appends a list predicates to the AdminRoleUpdate builder.
func (_u *AdminRoleUpdate) Where(ps ...predicate.AdminRole) *AdminRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminRoleUpdate) SetCreatedAt(v time.Time) *AdminRoleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableCreatedAt(v *time.Time) *AdminRoleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminRoleUpdate) SetUpdatedAt(v time.Time) *AdminRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AdminRoleUpdate) SetName(v string) *AdminRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableName(v *string) *AdminRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *AdminRoleUpdate) SetCode(v string) *AdminRoleUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableCode(v *string) *AdminRoleUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *AdminRoleUpdate) SetDesc(v string) *AdminRoleUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableDesc(v *string) *AdminRoleUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *AdminRoleUpdate) ClearDesc() *AdminRoleUpdate {
	_u.mutation.ClearDesc()
	return _u
}

// SetDataScope sets the "data_scope" field.
func (_u *AdminRoleUpdate) SetDataScope(v int) *AdminRoleUpdate {
	_u.mutation.ResetDataScope()
	_u.mutation.SetDataScope(v)
	return _u
}

// SetNillableDataScope sets the "data_scope" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableDataScope(v *int) *AdminRoleUpdate {
	if v != nil {
		_u.SetDataScope(*v)
	}
	return _u
}

// AddDataScope adds value to the "data_scope" field.
func (_u *AdminRoleUpdate) AddDataScope(v int) *AdminRoleUpdate {
	_u.mutation.AddDataScope(v)
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *AdminRoleUpdate) SetIsSystem(v bool) *AdminRoleUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableIsSystem(v *bool) *AdminRoleUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminRoleUpdate) SetIsActive(v bool) *AdminRoleUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableIsActive(v *bool) *AdminRoleUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AdminRoleUpdate) SetSort(v int) *AdminRoleUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AdminRoleUpdate) SetNillableSort(v *int) *AdminRoleUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AdminRoleUpdate) AddSort(v int) *AdminRoleUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// Mutation returns the AdminRoleMutation object of the builder.
func (_u *AdminRoleUpdate) Mutation() *AdminRoleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminRoleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adminrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := adminrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "AdminRole.code": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminrole.Table, adminrole.Columns, sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminrole.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(adminrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(adminrole.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(adminrole.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.DataScope(); ok {
		_spec.SetField(adminrole.FieldDataScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDataScope(); ok {
		_spec.AddField(adminrole.FieldDataScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(adminrole.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminrole.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(adminrole.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(adminrole.FieldSort, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminRoleUpdateOne is the builder for updating a single AdminRole entity.
type AdminRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminRoleMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminRoleUpdateOne) SetCreatedAt(v time.Time) *AdminRoleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableCreatedAt(v *time.Time) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminRoleUpdateOne) SetUpdatedAt(v time.Time) *AdminRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AdminRoleUpdateOne) SetName(v string) *AdminRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableName(v *string) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *AdminRoleUpdateOne) SetCode(v string) *AdminRoleUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableCode(v *string) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *AdminRoleUpdateOne) SetDesc(v string) *AdminRoleUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableDesc(v *string) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *AdminRoleUpdateOne) ClearDesc() *AdminRoleUpdateOne {
	_u.mutation.ClearDesc()
	return _u
}

// SetDataScope sets the "data_scope" field.
func (_u *AdminRoleUpdateOne) SetDataScope(v int) *AdminRoleUpdateOne {
	_u.mutation.ResetDataScope()
	_u.mutation.SetDataScope(v)
	return _u
}

// SetNillableDataScope sets the "data_scope" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableDataScope(v *int) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetDataScope(*v)
	}
	return _u
}

// AddDataScope adds value to the "data_scope" field.
func (_u *AdminRoleUpdateOne) AddDataScope(v int) *AdminRoleUpdateOne {
	_u.mutation.AddDataScope(v)
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *AdminRoleUpdateOne) SetIsSystem(v bool) *AdminRoleUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableIsSystem(v *bool) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminRoleUpdateOne) SetIsActive(v bool) *AdminRoleUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableIsActive(v *bool) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AdminRoleUpdateOne) SetSort(v int) *AdminRoleUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AdminRoleUpdateOne) SetNillableSort(v *int) *AdminRoleUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AdminRoleUpdateOne) AddSort(v int) *AdminRoleUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// Mutation returns the AdminRoleMutation object of the builder.
func (_u *AdminRoleUpdateOne) Mutation() *AdminRoleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminRoleUpdate builder.
func (_u *AdminRoleUpdateOne) Where(ps ...predicate.AdminRole) *AdminRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminRoleUpdateOne) Select(field string, fields ...string) *AdminRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminRole entity.
func (_u *AdminRoleUpdateOne) Save(ctx context.Context) (*AdminRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminRoleUpdateOne) SaveX(ctx context.Context) *AdminRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adminrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminRole.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := adminrole.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "AdminRole.code": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminRoleUpdateOne) sqlSave(ctx context.Context) (_node *AdminRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminrole.Table, adminrole.Columns, sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminrole.FieldID)
		for _, f := range fields {
			if !adminrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminrole.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(adminrole.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(adminrole.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(adminrole.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.DataScope(); ok {
		_spec.SetField(adminrole.FieldDataScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDataScope(); ok {
		_spec.AddField(adminrole.FieldDataScope, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(adminrole.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminrole.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(adminrole.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(adminrole.FieldSort, field.TypeInt, value)
	}
	_node = &AdminRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
