// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminroledept"
)

// AdminRoleDeptCreate is the builder for creating a AdminRoleDept entity.
type AdminRoleDeptCreate struct {
	config
	mutation *AdminRoleDeptMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminRoleDeptCreate) SetCreatedAt(v time.Time) *AdminRoleDeptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminRoleDeptCreate) SetNillableCreatedAt(v *time.Time) *AdminRoleDeptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminRoleDeptCreate) SetUpdatedAt(v time.Time) *AdminRoleDeptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminRoleDeptCreate) SetNillableUpdatedAt(v *time.Time) *AdminRoleDeptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AdminRoleDeptCreate) SetDeletedAt(v time.Time) *AdminRoleDeptCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AdminRoleDeptCreate) SetNillableDeletedAt(v *time.Time) *AdminRoleDeptCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *AdminRoleDeptCreate) SetRoleID(v int64) *AdminRoleDeptCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetDeptID sets the "dept_id" field.
func (_c *AdminRoleDeptCreate) SetDeptID(v int64) *AdminRoleDeptCreate {
	_c.mutation.SetDeptID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AdminRoleDeptCreate) SetID(v int64) *AdminRoleDeptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AdminRoleDeptMutation object of the builder.
func (_c *AdminRoleDeptCreate) Mutation() *AdminRoleDeptMutation {
	return _c.mutation
}

// Save creates the AdminRoleDept in the database.
func (_c *AdminRoleDeptCreate) Save(ctx context.Context) (*AdminRoleDept, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminRoleDeptCreate) SaveX(ctx context.Context) *AdminRoleDept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminRoleDeptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminRoleDeptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminRoleDeptCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if adminroledept.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminroledept.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := adminroledept.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if adminroledept.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminroledept.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adminroledept.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminRoleDeptCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminRoleDept.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminRoleDept.updated_at"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "AdminRoleDept.role_id"`)}
	}
	if v, ok := _c.mutation.RoleID(); ok {
		if err := adminroledept.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "AdminRoleDept.role_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeptID(); !ok {
		return &ValidationError{Name: "dept_id", err: errors.New(`ent: missing required field "AdminRoleDept.dept_id"`)}
	}
	if v, ok := _c.mutation.DeptID(); ok {
		if err := adminroledept.DeptIDValidator(v); err != nil {
			return &ValidationError{Name: "dept_id", err: fmt.Errorf(`ent: validator failed for field "AdminRoleDept.dept_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := adminroledept.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AdminRoleDept.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AdminRoleDeptCreate) sqlSave(ctx context.Context) (*AdminRoleDept, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminRoleDeptCreate) createSpec() (*AdminRoleDept, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminRoleDept{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminroledept.Table, sqlgraph.NewFieldSpec(adminroledept.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminroledept.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminroledept.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(adminroledept.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(adminroledept.FieldRoleID, field.TypeInt64, value)
		_node.RoleID = value
	}
	if value, ok := _c.mutation.DeptID(); ok {
		_spec.SetField(adminroledept.FieldDeptID, field.TypeInt64, value)
		_node.DeptID = value
	}
	return _node, _spec
}

// AdminRoleDeptCreateBulk is the builder for creating many AdminRoleDept entities in bulk.
type AdminRoleDeptCreateBulk struct {
	config
	err      error
	builders []*AdminRoleDeptCreate
}

// Save creates the AdminRoleDept entities in the database.
func (_c *AdminRoleDeptCreateBulk) Save(ctx context.Context) ([]*AdminRoleDept, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminRoleDept, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminRoleDeptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminRoleDeptCreateBulk) SaveX(ctx context.Context) []*AdminRoleDept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminRoleDeptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminRoleDeptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
