// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yuwen002/go-meteor-cms/ent/adminpermission"
	"github.com/yuwen002/go-meteor-cms/ent/adminrole"
	"github.com/yuwen002/go-meteor-cms/ent/adminrolepermission"
)

// 角色权限关联表
type AdminRolePermission struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 角色ID，关联 admin_roles.id
	RoleID int64 `json:"role_id,omitempty"`
	// 权限ID，关联 admin_permissions.id
	PermissionID int64 `json:"permission_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AdminRolePermissionQuery when eager-loading is set.
	Edges        AdminRolePermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AdminRolePermissionEdges holds the relations/edges for other nodes in the graph.
type AdminRolePermissionEdges struct {
	// Role holds the value of the role edge.
	Role *AdminRole `json:"role,omitempty"`
	// Permission holds the value of the permission edge.
	Permission *AdminPermission `json:"permission,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminRolePermissionEdges) RoleOrErr() (*AdminRole, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: adminrole.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// PermissionOrErr returns the Permission value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AdminRolePermissionEdges) PermissionOrErr() (*AdminPermission, error) {
	if e.Permission != nil {
		return e.Permission, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: adminpermission.Label}
	}
	return nil, &NotLoadedError{edge: "permission"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminRolePermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminrolepermission.FieldID, adminrolepermission.FieldRoleID, adminrolepermission.FieldPermissionID:
			values[i] = new(sql.NullInt64)
		case adminrolepermission.FieldCreatedAt, adminrolepermission.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminRolePermission fields.
func (_m *AdminRolePermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminrolepermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminrolepermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adminrolepermission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adminrolepermission.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = value.Int64
			}
		case adminrolepermission.FieldPermissionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminRolePermission.
// This includes values selected through modifiers, order, etc.
func (_m *AdminRolePermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the AdminRolePermission entity.
func (_m *AdminRolePermission) QueryRole() *AdminRoleQuery {
	return NewAdminRolePermissionClient(_m.config).QueryRole(_m)
}

// QueryPermission queries the "permission" edge of the AdminRolePermission entity.
func (_m *AdminRolePermission) QueryPermission() *AdminPermissionQuery {
	return NewAdminRolePermissionClient(_m.config).QueryPermission(_m)
}

// Update returns a builder for updating this AdminRolePermission.
// Note that you need to call AdminRolePermission.Unwrap() before calling this method if this AdminRolePermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminRolePermission) Update() *AdminRolePermissionUpdateOne {
	return NewAdminRolePermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminRolePermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminRolePermission) Unwrap() *AdminRolePermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminRolePermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminRolePermission) String() string {
	var builder strings.Builder
	builder.WriteString("AdminRolePermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("permission_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PermissionID))
	builder.WriteByte(')')
	return builder.String()
}

// AdminRolePermissions is a parsable slice of AdminRolePermission.
type AdminRolePermissions []*AdminRolePermission
