// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminpermission"
	"github.com/yuwen002/go-meteor-cms/ent/predicate"
)

// AdminPermissionUpdate is the builder for updating AdminPermission entities.
type AdminPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *AdminPermissionMutation
}

// Where appends a list predicates to the AdminPermissionUpdate builder.
func (_u *AdminPermissionUpdate) Where(ps ...predicate.AdminPermission) *AdminPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminPermissionUpdate) SetCreatedAt(v time.Time) *AdminPermissionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableCreatedAt(v *time.Time) *AdminPermissionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminPermissionUpdate) SetUpdatedAt(v time.Time) *AdminPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminPermissionUpdate) SetDeletedAt(v time.Time) *AdminPermissionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableDeletedAt(v *time.Time) *AdminPermissionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminPermissionUpdate) ClearDeletedAt() *AdminPermissionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *AdminPermissionUpdate) SetName(v string) *AdminPermissionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableName(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *AdminPermissionUpdate) SetParentID(v int64) *AdminPermissionUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableParentID(v *int64) *AdminPermissionUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *AdminPermissionUpdate) ClearParentID() *AdminPermissionUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetType sets the "type" field.
func (_u *AdminPermissionUpdate) SetType(v int) *AdminPermissionUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableType(v *int) *AdminPermissionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *AdminPermissionUpdate) AddType(v int) *AdminPermissionUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *AdminPermissionUpdate) SetPath(v string) *AdminPermissionUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillablePath(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetComponent sets the "component" field.
func (_u *AdminPermissionUpdate) SetComponent(v string) *AdminPermissionUpdate {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableComponent(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AdminPermissionUpdate) SetIcon(v string) *AdminPermissionUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableIcon(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AdminPermissionUpdate) SetMethod(v string) *AdminPermissionUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableMethod(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *AdminPermissionUpdate) SetAPIPath(v string) *AdminPermissionUpdate {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableAPIPath(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// SetPermission sets the "permission" field.
func (_u *AdminPermissionUpdate) SetPermission(v string) *AdminPermissionUpdate {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillablePermission(v *string) *AdminPermissionUpdate {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminPermissionUpdate) SetIsActive(v bool) *AdminPermissionUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableIsActive(v *bool) *AdminPermissionUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AdminPermissionUpdate) SetSort(v int) *AdminPermissionUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AdminPermissionUpdate) SetNillableSort(v *int) *AdminPermissionUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AdminPermissionUpdate) AddSort(v int) *AdminPermissionUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetParent sets the "parent" edge to the AdminPermission entity.
func (_u *AdminPermissionUpdate) SetParent(v *AdminPermission) *AdminPermissionUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the AdminPermission entity by IDs.
func (_u *AdminPermissionUpdate) AddChildIDs(ids ...int64) *AdminPermissionUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the AdminPermission entity.
func (_u *AdminPermissionUpdate) AddChildren(v ...*AdminPermission) *AdminPermissionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_u *AdminPermissionUpdate) Mutation() *AdminPermissionMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the AdminPermission entity.
func (_u *AdminPermissionUpdate) ClearParent() *AdminPermissionUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the AdminPermission entity.
func (_u *AdminPermissionUpdate) ClearChildren() *AdminPermissionUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to AdminPermission entities by IDs.
func (_u *AdminPermissionUpdate) RemoveChildIDs(ids ...int64) *AdminPermissionUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to AdminPermission entities.
func (_u *AdminPermissionUpdate) RemoveChildren(v ...*AdminPermission) *AdminPermissionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminPermissionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adminpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminpermission.Table, adminpermission.Columns, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminpermission.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminpermission.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminpermission.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminpermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(adminpermission.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(adminpermission.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(adminpermission.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(adminpermission.FieldComponent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(adminpermission.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(adminpermission.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(adminpermission.FieldAPIPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(adminpermission.FieldPermission, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminpermission.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(adminpermission.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(adminpermission.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.ParentTable,
			Columns: []string{adminpermission.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.ParentTable,
			Columns: []string{adminpermission.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.ChildrenTable,
			Columns: []string{adminpermission.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.ChildrenTable,
			Columns: []string{adminpermission.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.ChildrenTable,
			Columns: []string{adminpermission.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminPermissionUpdateOne is the builder for updating a single AdminPermission entity.
type AdminPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminPermissionMutation
}

// SetCreatedAt sets the "created_at" field.
func (_u *AdminPermissionUpdateOne) SetCreatedAt(v time.Time) *AdminPermissionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableCreatedAt(v *time.Time) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminPermissionUpdateOne) SetUpdatedAt(v time.Time) *AdminPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminPermissionUpdateOne) SetDeletedAt(v time.Time) *AdminPermissionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableDeletedAt(v *time.Time) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminPermissionUpdateOne) ClearDeletedAt() *AdminPermissionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *AdminPermissionUpdateOne) SetName(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableName(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *AdminPermissionUpdateOne) SetParentID(v int64) *AdminPermissionUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableParentID(v *int64) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *AdminPermissionUpdateOne) ClearParentID() *AdminPermissionUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetType sets the "type" field.
func (_u *AdminPermissionUpdateOne) SetType(v int) *AdminPermissionUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableType(v *int) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *AdminPermissionUpdateOne) AddType(v int) *AdminPermissionUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetPath sets the "path" field.
func (_u *AdminPermissionUpdateOne) SetPath(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillablePath(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetComponent sets the "component" field.
func (_u *AdminPermissionUpdateOne) SetComponent(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableComponent(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *AdminPermissionUpdateOne) SetIcon(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableIcon(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *AdminPermissionUpdateOne) SetMethod(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableMethod(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetAPIPath sets the "api_path" field.
func (_u *AdminPermissionUpdateOne) SetAPIPath(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetAPIPath(v)
	return _u
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableAPIPath(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetAPIPath(*v)
	}
	return _u
}

// SetPermission sets the "permission" field.
func (_u *AdminPermissionUpdateOne) SetPermission(v string) *AdminPermissionUpdateOne {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillablePermission(v *string) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *AdminPermissionUpdateOne) SetIsActive(v bool) *AdminPermissionUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableIsActive(v *bool) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *AdminPermissionUpdateOne) SetSort(v int) *AdminPermissionUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *AdminPermissionUpdateOne) SetNillableSort(v *int) *AdminPermissionUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *AdminPermissionUpdateOne) AddSort(v int) *AdminPermissionUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetParent sets the "parent" edge to the AdminPermission entity.
func (_u *AdminPermissionUpdateOne) SetParent(v *AdminPermission) *AdminPermissionUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the AdminPermission entity by IDs.
func (_u *AdminPermissionUpdateOne) AddChildIDs(ids ...int64) *AdminPermissionUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the AdminPermission entity.
func (_u *AdminPermissionUpdateOne) AddChildren(v ...*AdminPermission) *AdminPermissionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (_u *AdminPermissionUpdateOne) Mutation() *AdminPermissionMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the AdminPermission entity.
func (_u *AdminPermissionUpdateOne) ClearParent() *AdminPermissionUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the AdminPermission entity.
func (_u *AdminPermissionUpdateOne) ClearChildren() *AdminPermissionUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to AdminPermission entities by IDs.
func (_u *AdminPermissionUpdateOne) RemoveChildIDs(ids ...int64) *AdminPermissionUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to AdminPermission entities.
func (_u *AdminPermissionUpdateOne) RemoveChildren(v ...*AdminPermission) *AdminPermissionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the AdminPermissionUpdate builder.
func (_u *AdminPermissionUpdateOne) Where(ps ...predicate.AdminPermission) *AdminPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminPermissionUpdateOne) Select(field string, fields ...string) *AdminPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminPermission entity.
func (_u *AdminPermissionUpdateOne) Save(ctx context.Context) (*AdminPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminPermissionUpdateOne) SaveX(ctx context.Context) *AdminPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := adminpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := adminpermission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AdminPermission.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminPermissionUpdateOne) sqlSave(ctx context.Context) (_node *AdminPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminpermission.Table, adminpermission.Columns, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminpermission.FieldID)
		for _, f := range fields {
			if !adminpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(adminpermission.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminpermission.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminpermission.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(adminpermission.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(adminpermission.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(adminpermission.FieldType, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(adminpermission.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(adminpermission.FieldComponent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(adminpermission.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(adminpermission.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIPath(); ok {
		_spec.SetField(adminpermission.FieldAPIPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(adminpermission.FieldPermission, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(adminpermission.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(adminpermission.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(adminpermission.FieldSort, field.TypeInt, value)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.ParentTable,
			Columns: []string{adminpermission.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adminpermission.ParentTable,
			Columns: []string{adminpermission.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.ChildrenTable,
			Columns: []string{adminpermission.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.ChildrenTable,
			Columns: []string{adminpermission.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.ChildrenTable,
			Columns: []string{adminpermission.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdminPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
