// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/adminrolepermission"
)

// AdminRolePermissionCreate is the builder for creating a AdminRolePermission entity.
type AdminRolePermissionCreate struct {
	config
	mutation *AdminRolePermissionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminRolePermissionCreate) SetCreatedAt(v time.Time) *AdminRolePermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminRolePermissionCreate) SetNillableCreatedAt(v *time.Time) *AdminRolePermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminRolePermissionCreate) SetUpdatedAt(v time.Time) *AdminRolePermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminRolePermissionCreate) SetNillableUpdatedAt(v *time.Time) *AdminRolePermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AdminRolePermissionCreate) SetDeletedAt(v time.Time) *AdminRolePermissionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AdminRolePermissionCreate) SetNillableDeletedAt(v *time.Time) *AdminRolePermissionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *AdminRolePermissionCreate) SetRoleID(v int64) *AdminRolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *AdminRolePermissionCreate) SetPermissionID(v int64) *AdminRolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetDummy sets the "dummy" field.
func (_c *AdminRolePermissionCreate) SetDummy(v uint8) *AdminRolePermissionCreate {
	_c.mutation.SetDummy(v)
	return _c
}

// SetNillableDummy sets the "dummy" field if the given value is not nil.
func (_c *AdminRolePermissionCreate) SetNillableDummy(v *uint8) *AdminRolePermissionCreate {
	if v != nil {
		_c.SetDummy(*v)
	}
	return _c
}

// Mutation returns the AdminRolePermissionMutation object of the builder.
func (_c *AdminRolePermissionCreate) Mutation() *AdminRolePermissionMutation {
	return _c.mutation
}

// Save creates the AdminRolePermission in the database.
func (_c *AdminRolePermissionCreate) Save(ctx context.Context) (*AdminRolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminRolePermissionCreate) SaveX(ctx context.Context) *AdminRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminRolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminRolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminRolePermissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminrolepermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adminrolepermission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Dummy(); !ok {
		v := adminrolepermission.DefaultDummy
		_c.mutation.SetDummy(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminRolePermissionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminRolePermission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminRolePermission.updated_at"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "AdminRolePermission.role_id"`)}
	}
	if v, ok := _c.mutation.RoleID(); ok {
		if err := adminrolepermission.RoleIDValidator(v); err != nil {
			return &ValidationError{Name: "role_id", err: fmt.Errorf(`ent: validator failed for field "AdminRolePermission.role_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "AdminRolePermission.permission_id"`)}
	}
	if v, ok := _c.mutation.PermissionID(); ok {
		if err := adminrolepermission.PermissionIDValidator(v); err != nil {
			return &ValidationError{Name: "permission_id", err: fmt.Errorf(`ent: validator failed for field "AdminRolePermission.permission_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Dummy(); !ok {
		return &ValidationError{Name: "dummy", err: errors.New(`ent: missing required field "AdminRolePermission.dummy"`)}
	}
	return nil
}

func (_c *AdminRolePermissionCreate) sqlSave(ctx context.Context) (*AdminRolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminRolePermissionCreate) createSpec() (*AdminRolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminRolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminrolepermission.Table, sqlgraph.NewFieldSpec(adminrolepermission.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminrolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminrolepermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(adminrolepermission.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(adminrolepermission.FieldRoleID, field.TypeInt64, value)
		_node.RoleID = value
	}
	if value, ok := _c.mutation.PermissionID(); ok {
		_spec.SetField(adminrolepermission.FieldPermissionID, field.TypeInt64, value)
		_node.PermissionID = value
	}
	if value, ok := _c.mutation.Dummy(); ok {
		_spec.SetField(adminrolepermission.FieldDummy, field.TypeUint8, value)
		_node.Dummy = value
	}
	return _node, _spec
}

// AdminRolePermissionCreateBulk is the builder for creating many AdminRolePermission entities in bulk.
type AdminRolePermissionCreateBulk struct {
	config
	err      error
	builders []*AdminRolePermissionCreate
}

// Save creates the AdminRolePermission entities in the database.
func (_c *AdminRolePermissionCreateBulk) Save(ctx context.Context) ([]*AdminRolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminRolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminRolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminRolePermissionCreateBulk) SaveX(ctx context.Context) []*AdminRolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminRolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminRolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
