// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yuwen002/go-meteor-cms/ent/tokenblacklist"
)

// TokenBlacklistCreate is the builder for creating a TokenBlacklist entity.
type TokenBlacklistCreate struct {
	config
	mutation *TokenBlacklistMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TokenBlacklistCreate) SetCreatedAt(v time.Time) *TokenBlacklistCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TokenBlacklistCreate) SetNillableCreatedAt(v *time.Time) *TokenBlacklistCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TokenBlacklistCreate) SetUpdatedAt(v time.Time) *TokenBlacklistCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TokenBlacklistCreate) SetNillableUpdatedAt(v *time.Time) *TokenBlacklistCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *TokenBlacklistCreate) SetTokenHash(v string) *TokenBlacklistCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *TokenBlacklistCreate) SetToken(v string) *TokenBlacklistCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_c *TokenBlacklistCreate) SetNillableToken(v *string) *TokenBlacklistCreate {
	if v != nil {
		_c.SetToken(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *TokenBlacklistCreate) SetExpiredAt(v time.Time) *TokenBlacklistCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TokenBlacklistCreate) SetID(v int64) *TokenBlacklistCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TokenBlacklistMutation object of the builder.
func (_c *TokenBlacklistCreate) Mutation() *TokenBlacklistMutation {
	return _c.mutation
}

// Save creates the TokenBlacklist in the database.
func (_c *TokenBlacklistCreate) Save(ctx context.Context) (*TokenBlacklist, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TokenBlacklistCreate) SaveX(ctx context.Context) *TokenBlacklist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokenBlacklistCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokenBlacklistCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TokenBlacklistCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tokenblacklist.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tokenblacklist.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TokenBlacklistCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TokenBlacklist.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TokenBlacklist.updated_at"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "TokenBlacklist.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := tokenblacklist.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "TokenBlacklist.token_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := tokenblacklist.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "TokenBlacklist.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "TokenBlacklist.expired_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := tokenblacklist.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TokenBlacklist.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TokenBlacklistCreate) sqlSave(ctx context.Context) (*TokenBlacklist, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TokenBlacklistCreate) createSpec() (*TokenBlacklist, *sqlgraph.CreateSpec) {
	var (
		_node = &TokenBlacklist{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tokenblacklist.Table, sqlgraph.NewFieldSpec(tokenblacklist.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tokenblacklist.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tokenblacklist.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(tokenblacklist.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(tokenblacklist.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(tokenblacklist.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	return _node, _spec
}

// TokenBlacklistCreateBulk is the builder for creating many TokenBlacklist entities in bulk.
type TokenBlacklistCreateBulk struct {
	config
	err      error
	builders []*TokenBlacklistCreate
}

// Save creates the TokenBlacklist entities in the database.
func (_c *TokenBlacklistCreateBulk) Save(ctx context.Context) ([]*TokenBlacklist, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TokenBlacklist, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TokenBlacklistMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TokenBlacklistCreateBulk) SaveX(ctx context.Context) []*TokenBlacklist {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokenBlacklistCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokenBlacklistCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
