// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/yuwen002/go-meteor-cms/ent"
	"github.com/yuwen002/go-meteor-cms/ent/adminpermission"
	"github.com/yuwen002/go-meteor-cms/ent/adminrole"
	"github.com/yuwen002/go-meteor-cms/ent/adminrolepermission"
	"github.com/yuwen002/go-meteor-cms/ent/adminuser"
	"github.com/yuwen002/go-meteor-cms/ent/adminuserrole"
	"github.com/yuwen002/go-meteor-cms/ent/predicate"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The AdminPermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type AdminPermissionFunc func(context.Context, *ent.AdminPermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AdminPermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AdminPermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AdminPermissionQuery", q)
}

// The TraverseAdminPermission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAdminPermission func(context.Context, *ent.AdminPermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAdminPermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAdminPermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AdminPermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AdminPermissionQuery", q)
}

// The AdminRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type AdminRoleFunc func(context.Context, *ent.AdminRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AdminRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AdminRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AdminRoleQuery", q)
}

// The TraverseAdminRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAdminRole func(context.Context, *ent.AdminRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAdminRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAdminRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AdminRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AdminRoleQuery", q)
}

// The AdminRolePermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type AdminRolePermissionFunc func(context.Context, *ent.AdminRolePermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AdminRolePermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AdminRolePermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AdminRolePermissionQuery", q)
}

// The TraverseAdminRolePermission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAdminRolePermission func(context.Context, *ent.AdminRolePermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAdminRolePermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAdminRolePermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AdminRolePermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AdminRolePermissionQuery", q)
}

// The AdminUserFunc type is an adapter to allow the use of ordinary function as a Querier.
type AdminUserFunc func(context.Context, *ent.AdminUserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AdminUserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AdminUserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AdminUserQuery", q)
}

// The TraverseAdminUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAdminUser func(context.Context, *ent.AdminUserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAdminUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAdminUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AdminUserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AdminUserQuery", q)
}

// The AdminUserRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type AdminUserRoleFunc func(context.Context, *ent.AdminUserRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AdminUserRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AdminUserRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AdminUserRoleQuery", q)
}

// The TraverseAdminUserRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAdminUserRole func(context.Context, *ent.AdminUserRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAdminUserRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAdminUserRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AdminUserRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AdminUserRoleQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.AdminPermissionQuery:
		return &query[*ent.AdminPermissionQuery, predicate.AdminPermission, adminpermission.OrderOption]{typ: ent.TypeAdminPermission, tq: q}, nil
	case *ent.AdminRoleQuery:
		return &query[*ent.AdminRoleQuery, predicate.AdminRole, adminrole.OrderOption]{typ: ent.TypeAdminRole, tq: q}, nil
	case *ent.AdminRolePermissionQuery:
		return &query[*ent.AdminRolePermissionQuery, predicate.AdminRolePermission, adminrolepermission.OrderOption]{typ: ent.TypeAdminRolePermission, tq: q}, nil
	case *ent.AdminUserQuery:
		return &query[*ent.AdminUserQuery, predicate.AdminUser, adminuser.OrderOption]{typ: ent.TypeAdminUser, tq: q}, nil
	case *ent.AdminUserRoleQuery:
		return &query[*ent.AdminUserRoleQuery, predicate.AdminUserRole, adminuserrole.OrderOption]{typ: ent.TypeAdminUserRole, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
